export const activityTags = {
    SIGNUP: "Signup",
    LOGIN: "Login",
    PROFILE_UPDATE: "Profile_Update",
    DELETE_USER: "User_Delete",
    ADMIN_ADDED: "Admin_Added",
    ADMIN_LOGIN: "Admin_Login",
    BATTLE_RESULT_ADDED: "Battle_Result_Added",
    BATTLE_RESULT_UPDATED: "Battle_Result_Updated",
    BATTLE_ADDED: "Battle_Added",
    BATTLE_JOINED: "Battle_Joined",
    ROOM_CODE_ADDED: "Room_Code_Added",
    BATTLE_DELETED: "Battle_Deleted",
    PAYMENT_ADDED: "Payment_Added",
    PAYMENT_UPDATED: "Payment_Updated",
    WALLET_CREATED: "Wallet_Created",
    WALLET_UPDATED: "Wallet_Updated",
    WINING_CASH_WALLET_CREATED: "Wining_Case_Wallet_Created",
    WINING_CASH_WALLET_UPDATED: "Wining_Case_Wallet_Updated",
    WITHDRAWAL_REQUEST: "Withdrawal_Request",
    WITHDRAWAL_REQUEST_UPDATED: "Withdrawal_Request_Updated",
    BATTLE_REQUEST_RAISED: "Battle_Result_Raised",
    BATTLE_REQUEST_ACCEPTED: "Battle_Result_Accepted",
    BATTLE_REQUEST_DELETED: "Battle_Result_Deleted",
    BATTLE_REQUEST_CANCEL: "Battle_Result_Cancel",

}